[versions]
# libraries
junit = "4.13.2"
kotlinLogging = "7.0.0"
picocli = "4.7.6"

# plugins
kotlin = "2.0.21"
shadowJar = "8.3.5"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
jackson = "com.fasterxml.jackson.module:jackson-module-kotlin:2.18.1"
jackson-yaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.1"
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
slf4j = "org.slf4j:slf4j-api:2.0.16"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.16"
velocity = "org.apache.velocity:velocity-engine-core:2.3"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadowJar" }
