[versions]
# libraries
junit = "4.13.2"

# plugins
kotlin = "2.0.21"
[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
